# EXE = locus_composition locus_composition_discrete pileup_stats locus_basequal_dist \
# 	simulate_pileup simulate_basecomp quantile_test test_dirichlet

locus_composition : locus_composition.o metropolis.o sampling.o integrands.o tools.o \
	error_estimate.o pileup_tools.o stats_tools.o dirichlet.o slice_sampling.o hilbert.o \
	simulation.o transformation.o nucleotide_stats.o nucleotide_reader.o base_qual_strand_reader.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

locus_composition_discrete : locus_composition_discrete.o integrands.o tools.o \
	error_estimate.o transformation.o dirichlet.o pileup_tools.o stats_tools.o \
	nucleotide_stats.o nucleotide_reader.o base_qual_strand_reader.o simulation.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

locus_basequal_dist : locus_basequal_dist.o pileup_tools.o error_estimate.o dirichlet.o \
	transformation.o tools.o stats_tools.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

simulate_pileup : simulate_pileup.o error_estimate.o dirichlet.o tools.o simulation.o \
	stats_tools.o transformation.o nucleotide_stats.o nucleotide_reader.o \
	base_qual_strand_reader.o pileup_tools.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

simulate_basecomp : simulate_basecomp.o stats_tools.o simulation.o tools.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

pileup_stats : pileup_stats.o tools.o pileup_tools.o stats_tools.o nucleotide_stats.o nucleotide_reader.o \
	 base_qual_strand_reader.o	
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

stats_test : stats_test.o stats_tools.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

